version: '3.4'

services:
  ae.notice.webapp:
    image: ${DOCKER_REGISTRY-}aenoticewebapp
    build:
      context: .
      dockerfile: src/AE.Notice.WebApp/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "123qwe!@#QWE"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "board"
